### ISSUE TITLE
colors on windows machine causing vagrant to fail with missing vagrant-winrm plugin

### ISSUE THREAD

**Issue by phillipbroberts** [test-kitchen/kitchen-vagrant#240]
This could possibly be a duplicate #207 - however, someone said it has been resolved. 

When trying to run kitchen <command> against a Windows machine, we are seeing failures in finding the vagrant-winrm plugin. In digging I found this code that searches for its presence: 

`def winrm_plugin_installed?
        return true if self.class.winrm_plugin_passed

```
    self.class.winrm_plugin_passed = run_silently(
      "#{config[:vagrant_binary]} plugin list", :cwd => Dir.pwd).
      split("\n").find { |line| line =~ /^vagrant-winrm\s+/ }
  end`
```

This regex would typically return: 

```
%x(vagrant plugin list).split("\n").find { |line| line =~ /^vagrant-winrm\s+/ }
"vagrant-winrm (0.7.0)"
```

On affected systems it returns as nil. Testing shown below: 

```
irb(main):001:0> %x(vagrant plugin list).split("\n").find { |line| line =~ /^vagrant-winrm\s+/ }
=> nil
irb(main):002:0> %x(vagrant plugin list).split("\n")
=> ["\e[0mvagrant-share (1.1.5, system)\e[0m", "\e[0mvagrant-winrm (0.7.0)\e[0m"] 

```

The \e[0m are color codes that are not properly being translated on this particular system. The affected user has attempted using --no-color as well as placing [Environment]::SetEnvironmentVariable("VAGRANT_NO_COLOR","false","Machine") in their vagrantfile.

**Comment by phillipbroberts** [comment]
PS C:\Users\fsmith\anything> kitchen converge
-----> Starting Kitchen (v1.10.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

PS C:\Users\fsmith\anything> chef exec irb
irb(main):001:0> %x(vagrant plugin list).split("\n").find { |line| line =~ /vagrant-winrm\s+/ }
=> "\e[0mvagrant-winrm (0.7.0)\e[0m"

**Comment by ivadim** [comment]
Have same issue on Windows 10 Anniversary Update
To workaround issue I changed regexp in c:\opscode\chefdk\embedded\lib\ruby\gems\2.1.0\gems\kitchen-vagrant-0.20.0\lib\kitchen\driver\vagrant.rb regarding @phillipbroberts comment

**Comment by computergeekheh** [comment]
Ivadim, could you please post the code change? I changed the regex as Phil did, but it did not solve my issue and was wondering if you changed it differently...

**Comment by phillipbroberts** [comment]
@computergeekheh meant to tag @ivadim

**Comment by ivadim** [comment]
Ah, sorry, not exact same regex. 
I changed to `/.*vagrant-winrm\s+/ `
``` 
def winrm_plugin_installed?
        return true if self.class.winrm_plugin_passed
        self.class.winrm_plugin_passed = run_silently(
          "#{config[:vagrant_binary]} plugin list", :cwd => Dir.pwd).
          split("\n").find { |line| line =~ /.*vagrant-winrm\s+/ }
end
```

**Comment by computergeekheh** [comment]
Thanks for the info. I am running Windows7, and I tried that regex without success.

Again, I thank you for this info. If anyone has any other suggestions, I will try those. If someone has a suggestion on how to remove the colors, or what gem this was added in, I would also be up for removing that as an option. Thanks again for the info.

**Comment by computergeekheh** [comment]
bump?

Anyone else have any thoughts on how to resolve this?

**Comment by Scoth42** [comment]
The tweak to the regex worked for me, but note that depending on specific versions of things it actually may be in c:\opscode\chefdk\embedded\lib\ruby\gems\**2.3.0**\gems\kitchen-vagrant-0.20.0\lib\kitchen\driver\vagrant.rb or another spot.

**Comment by cdbeard2016** [comment]
Just had the same issue on win 7 sp1 which was fixed by the regex change, can't thank you all enough, this has been beating me up for hours!

I did find that when running "kitchen init" a new kitchen-vagrant gem is installed on a different path from the chefdk directory you specify on install. I found it at %userprofile%/AppData/Local/chefdk/gem/ruby/2.3.0/gems/kitchen-vagrant-0.20.0/lib/kitchen/driver/vagrant.rb so if changing the regex doesn't work in your opscode directory have a look there as well. It might also be worth checking the gem paths by running "gem env" for any other locations. It seems that this gem gets refreshed each time you run "kitchen init" so i can see changing the regex manually becoming a bit of a pain until there is a more permanent fix!

**Comment by cheeseplus** [comment]
This still biting folks?

**Comment by davidski** [comment]
Afraid so. Just found this thread after working on test-kitchen/test-kitchen#1109. In my case, manually changing https://github.com/test-kitchen/kitchen-vagrant/blob/77de176c04a64c8fbb968aeca197e90082e874ef/lib/kitchen/driver/vagrant.rb#L538 to call `vagrant --no-color plugin list` enabled things to work. While I'm not sure why some systems are returning the escape codes and others are not, I'm happy to help debug this.

**Comment by Scoth42** [comment]
Just reinstalled stuff on a new box and had to come back here to remember how to fix it. Still happening with Vagrant 1.9.3 on Windows 10.

**Comment by silverl** [comment]
And still happening on Vagrant 1.9.5, Windows 10 Creators Update, and all dependencies are the latest/greatest available.

**Comment by silverl** [comment]
My workaround:

In `C:\opscode\chefdk\embedded\lib\ruby\gems\2.3.0\gems\kitchen-vagrant-1.1.0\lib\kitchen\driver\vagrant.rb`, I changed line 564 from this:

`split("\n").find { |line| line =~ /^vagrant-winrm\s+/ }`

to this

`split("\n").find { |line| line =~ /vagrant-winrm\s+/ }`

This "loosens up" the regex slightly and allows it to work on my machine.

**Comment by cheeseplus** [comment]
@silverl any chance you could PR that one? if not that seems like an easy enough fix and I should be able to get to it early next week (vacation time)

**Comment by silverl** [comment]
Done: https://github.com/test-kitchen/kitchen-vagrant/pull/309

**Comment by cheeseplus** [comment]
Closing this one as we've merged #309
